version: "3.7"

services:
  theia:
    build: 
      context: .
    container_name: "theia"
    ports:
      - '3000:3000'
      #- '8080:8080' # Dashboard
    volumes:
      - ./:/home/project:cached
